export const LOGIN_NO_TOKEN = "LOGIN_NO_TOKEN";
export const LOGIN_PROCESSING = "LOGIN_PROCESSING";
export const LOGIN_NOT_PROCESSING = "LOGIN_NOT_PROCESSING";
export const LOGIN_AUTHORIZE = "LOGIN_AUTHORIZE";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SIGN_UP = "LOGIN_SIGN_UP";
export const LOGIN_SET_AUTH = "LOGIN_SET_AUTH";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";

export const USERS_FETCHING = "USERS_FETCHING";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";
export const USERS_USER_TO_EDIT_SET = "USERS_USER_TO_EDIT_SET";
export const USERS_USER_TO_EDIT_FAILED = "USERS_USER_TO_EDIT_FAILED";
export const USERS_EDIT_USER_TO_EDIT = "USERS_EDIT_USER_TO_EDIT";
